function [rhs] = DuffingFilteredHamiltonianRHS(t,x,M)
rhs = [x(2); ...
        -M.a1*x(1)-M.nu*x(2)-M.a3*x(1).^3+M.F*cos(M.w*t)+x(3); ...
        M.wc^2*x(6)-M.wc*x(3); ...
        x(5)*(3*M.a3*x(1)^2+M.a1); ...
        M.nu*x(5)-x(4); ... 
        -x(5)+M.wc*x(6)];
end

