function [rhs] = ThreeDuffingRHS(t,x,M)
fcos = M.F*cos(M.w*t);
rhs = [x(2); ...
        -M.a1*x(1)-M.nu*x(2)-M.a3*x(1).^3+fcos-M.kc*(2*x(1)-x(3)-x(5));
        x(4); ...
        -M.a1*x(3)-M.nu*x(4)-M.a3*x(3).^3+fcos-M.kc*(2*x(3)-x(1)-x(5)); ... 
        x(6); ...
        -M.a1*x(5)-M.nu*x(6)-M.a3*x(5).^3+fcos-M.kc*(2*x(5)-x(1)-x(3))];
end

